version: "3"

tasks:
  gen-sso:
    desc: "Generate code from proto file sso"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  gen-game:
    desc: "Generate code from proto file game"
    cmds:
      - protoc -I proto proto/game/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative